/**
 * Writes registry items to the local .awesome-ai/registry/ directory.
 *
 * Used by both `awesome-ai add` (from fetched remote items) and
 * `awesome-ai sync` (from locally re-extracted items).
 */

import { promises as fs } from "fs"
import path from "path"
import type { RegistryItem } from "../registry/schema"
import { buildRegistryIndex } from "./registry-builder"

const DEFAULT_REGISTRY_DIR = ".awesome-ai/registry"

/**
 * Map a registry item type string to its plural directory name.
 */
function typeToDir(type: string): string | null {
	if (type === "registry:agent") return "agents"
	if (type === "registry:tool") return "tools"
	if (type === "registry:prompt") return "prompts"
	if (type === "registry:lib") return null // libs are embedded, not top-level
	return null
}

/**
 * Write a list of registry items to the local .awesome-ai/registry/ directory.
 *
 * Items are grouped by type and written individually. After writing, the
 * registry.json index for each touched type is regenerated by scanning
 * all existing JSON files in that type directory (additive, not destructive).
 */
export async function writeRegistryAtPath(
	registryDir: string,
	items: RegistryItem[],
): Promise<void> {
	const touchedTypes = new Set<string>()

	for (const item of items) {
		const dir = typeToDir(item.type)
		if (!dir) continue

		const itemDir = path.join(registryDir, dir)
		await fs.mkdir(itemDir, { recursive: true })

		const outputPath = path.join(itemDir, `${item.name}.json`)
		await fs.writeFile(
			outputPath,
			`${JSON.stringify(item, null, "\t")}\n`,
			"utf-8",
		)
		touchedTypes.add(dir)
	}

	// Regenerate registry.json index for each touched type
	for (const dir of touchedTypes) {
		await regenerateIndex(registryDir, dir)
	}
}

export async function writeLocalRegistry(
	cwd: string,
	items: RegistryItem[],
): Promise<void> {
	await writeRegistryAtPath(path.join(cwd, DEFAULT_REGISTRY_DIR), items)
}

/**
 * Regenerate the registry.json index for a given type by scanning
 * all existing item JSON files in the directory.
 */
async function regenerateIndex(
	registryDir: string,
	type: string,
): Promise<void> {
	const typeDir = path.join(registryDir, type)
	const entries = await fs.readdir(typeDir)

	const items: RegistryItem[] = []

	for (const entry of entries) {
		if (entry === "registry.json" || !entry.endsWith(".json")) continue

		const filePath = path.join(typeDir, entry)
		try {
			const content = await fs.readFile(filePath, "utf-8")
			const item = JSON.parse(content)
			items.push(item)
		} catch {
			// Skip malformed files
		}
	}

	const index = buildRegistryIndex(items, type)
	const indexPath = path.join(typeDir, "registry.json")
	await fs.writeFile(
		indexPath,
		`${JSON.stringify(index, null, "\t")}\n`,
		"utf-8",
	)
}
